The aim of this workbook is to explore the Integrated Gradients implementation.

In [ ]:
import captum.attr
import torch

In [ ]:
from model.attribution_methods.integrated_gradients import IntegratedGradients
from data.util.utils import DatasetMode

dataset = DryBean(mode=DatasetMode.TEST)

ig = IntegratedGradients(model.get_gradients_with_respect_to_inputs)

x,true_y = dataset[0]
model.eval()
pred_y = model(x)
print(true_y)
print(pred_y)

attribution_score = ig.attribute(x,target_label_index=None,n_steps=500)
print(attribution_score)




tensor([0., 0., 0., 1., 0., 0., 0.])
tensor([ -1.1628, -17.6076,  -5.6580,  12.4579,  -3.2940,   7.1996,   8.4602],
       grad_fn=<AddBackward0>)
tensor([-0.5787, -1.7392, -1.8341, -1.8474,  0.5648, -0.7242, -0.6304, -1.7664,
        -2.1227,  3.6250,  3.0621, -0.8239,  9.8495,  6.5152, -1.1935,  2.4330])


In [ ]:
dataset = DryBean(mode=DatasetMode.TEST)
x,true_y = dataset[0]
x = x.unsqueeze(0)
input = x.clone().detach().requires_grad_(True)

ig_captum = captum.attr.IntegratedGradients(model)

attributions = ig_captum.attribute(input,method="riemann_right", target=4,n_steps=500)
print(attributions)

In [ ]:
from evaluation import IntegratedGradientsEvaluator

evaluator = IntegratedGradientsEvaluator(model=model)
print(evaluator.mse_delta())

0


TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [ ]:
tensor = torch.tensor([4,2,3,1])
indices = tensor.argsort(descending=True)

print(tensor)
print(indices)

tensor[indices[0:3]]=0
print(tensor)

tensor([4, 2, 3, 1])
tensor([0, 2, 1, 3])
tensor([0, 0, 0, 1])
