In [7]:
import captum.attr
import torch

In [8]:
from data.datasets import DryBean
from model.training import train_model

model = train_model()[0]






Epoch nr.: 0
Test-Loss: 1.9354173683980753
Test-Accuracy: 0.19676945668135096
Train-Loss: 1.8060009542587134
Train-Accuracy: 0.2547759000734754
Epoch nr.: 1
Test-Loss: 1.6492115419510511
Test-Accuracy: 0.2591776798825257
Train-Loss: 1.3543557250526002
Train-Accuracy: 0.4254224834680382
Epoch nr.: 2
Test-Loss: 1.1127002643562898
Test-Accuracy: 0.5609397944199707
Train-Loss: 0.9959393425254065
Train-Accuracy: 0.5903747244673034
Epoch nr.: 3
Test-Loss: 0.8787975990981386
Test-Accuracy: 0.6262848751835536
Train-Loss: 0.7469629661332676
Train-Accuracy: 0.7355804555473916
Epoch nr.: 4
Test-Loss: 0.5332193672657013
Test-Accuracy: 0.8384728340675477
Train-Loss: 0.4415899863210695
Train-Accuracy: 0.855253490080823
Epoch nr.: 5
Test-Loss: 0.42286566457553215
Test-Accuracy: 0.8450807635829662
Train-Loss: 0.3460882633984702
Train-Accuracy: 0.8750918442321822
Epoch nr.: 6
Test-Loss: 0.32765743872749875
Test-Accuracy: 0.882525697503671
Train-Loss: 0.32166717127721667
Train-Accuracy: 0.88179647318148

In [10]:
from model.attribution_methods.integrated_gradients import IntegratedGradients
from data.util.utils import DatasetMode

dataset = DryBean(mode=DatasetMode.TEST)

ig = IntegratedGradients(model.get_gradients_with_respect_to_inputs)

x,true_y = dataset[0]
model.eval()
pred_y = model(x)
print(true_y)
print(pred_y)

attribution_score = ig.attribute(x,target_label_index=None,n_steps=500)
print(attribution_score)





tensor([0., 0., 0., 1., 0., 0., 0.])
tensor([ -1.1628, -17.6076,  -5.6580,  12.4579,  -3.2940,   7.1996,   8.4602],
       grad_fn=<AddBackward0>)
tensor([-0.5787, -1.7392, -1.8341, -1.8474,  0.5648, -0.7242, -0.6304, -1.7664,
        -2.1227,  3.6250,  3.0621, -0.8239,  9.8495,  6.5152, -1.1935,  2.4330])


In [11]:
dataset = DryBean(mode=DatasetMode.TEST)
x,true_y = dataset[0]
x = x.unsqueeze(0)
input = x.clone().detach().requires_grad_(True)

ig_captum = captum.attr.IntegratedGradients(model)

attributions = ig_captum.attribute(input,method="riemann_right", target=4,n_steps=500)
print(attributions)

tensor([[ 4.5494e-03, -3.8563e-01,  7.0007e-02, -4.5273e-01,  3.1659e+00,
          4.7413e+00,  2.2999e-02, -1.9549e-01,  5.1713e-01,  1.2624e-01,
          5.2115e-01, -5.7179e+00,  5.4327e+00, -2.8142e+00, -4.9261e+00,
         -6.3311e+00]], grad_fn=<MulBackward0>)


In [12]:
from evaluation import IntegratedGradientsEvaluator

evaluator = IntegratedGradientsEvaluator(model=model)
print(evaluator.mse_delta())

0


TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [13]:
tensor = torch.tensor([4,2,3,1])
indices = tensor.argsort(descending=True)

print(tensor)
print(indices)

tensor[indices[0:3]]=0
print(tensor)

tensor([4, 2, 3, 1])
tensor([0, 2, 1, 3])
tensor([0, 0, 0, 1])
